{
 "title": "42Segbot - Personal",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "person", "query": "SELECT login from users" }
  ]
 },
 "panels": [
  {
   "title": "Correction Points",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  login AS metric,\n  correction_point\nFROM over_time_data\nWHERE\n  $__timeFilter(created_at) AND\n  login = '$person'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Level",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  login AS metric,\n  level\nFROM over_time_data\nWHERE\n  $__timeFilter(created_at) AND\n  login = '$person'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Current Location",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  location\nFROM users\nwhere login = '$person'"
    }
   ]
  },
  {
   "title": "Ongoing Projects",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  project_name\nFROM\n  project_data\nWHERE\n  project_user = '$person'\nAND\n  project_status = 'in_progress'"
    }
   ]
  }
 ]
}