apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-mysql
  labels:
    run: mysql
spec:
  storageClassName: mysql
  capacity:
    storage: 700Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/mysql"
