apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    run: mysql
    app: ft_services
spec:
  selector:
    matchLabels:
      run: mysql
  template:
    metadata:
      labels:
        run: mysql
    spec:
      containers:
        - name: mysql
          image: services_mysql
          imagePullPolicy: Never
          ports:
            - name: sql
              containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: volume-mysql
      restartPolicy: Always
      volumes:
        - name: volume-mysql
          persistentVolumeClaim:
            claimName: claim-mysql
