#!/bin/bash

if [ "$3" = "1" ]
then
	FILECOUNT="$(find . -name '*.'$1 | wc -l | bc)"
	echo "${FILECOUNT} Files Matching"
	for ((I=1; I<=FILECOUNT; I++));
	do
		FILENAME[I]="$(find . -name '*.'$1 | sed ${I}'q;d' | awk -F/ '{print $NF}')"
	done
	for ((I=1; I<=FILECOUNT; I++));
	do
		mv ${FILENAME[I]} $2${FILENAME[I]}
		echo -e "Added Prefix to ${FILENAME[I]} [$I / $FILECOUNT]"
	done
fi

if [ "$3" = "2" ]
then
	FILECOUNT="$(find . -name '*.'$1 | wc -l | bc)"
	echo "${FILECOUNT} Files Matching"
	for ((I=1; I<=FILECOUNT; I++));
	do
		FILENAME1[I]="$(find . -name '*.'$1 | sed ${I}'q;d' | awk -F/ '{print $NF}' | sed s/'\'$2//g)"
		FILENAME2[I]="$(find . -name '*.'$1 | sed ${I}'q;d' | awk -F/ '{print $NF}')"
	done
	for ((I=1; I<=FILECOUNT; I++));
	do
		if [ "${FILENAME1[I]}" != "${FILENAME2[I]}" ]
		then
			mv ${FILENAME2[I]} ${FILENAME1[I]}
			echo -e "Removed Prefix to ${FILENAME2[I]} [$I / $FILECOUNT]"
		fi
	done
fi
