{
 "title": "Docker",
 "description": "Docker Metrics with influx and Telegraf",
 "tags": [
  "Docker",
  "Telegraf",
  "InfluxDB"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Host",
    "label": "Host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   },
   {
    "name": "Docker_Stack",
    "label": "Docker_Stack",
    "query": "SHOW TAG VALUES WITH KEY = \"docker.group\"  "
   }
  ]
 },
 "panels": [
  {
   "title": "Total Running Containers",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_running" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Running ft_services Containers",
   "type": "table",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "container_name" ], "type": "tag" }
     ],
     "measurement": "docker_container_mem",
     "query": "SELECT \"usage\" FROM \"docker_container_mem\" WHERE (\"docker.group\" =~ /^$Docker_Stack$/ AND \"host\" =~ /^$Host$/ AND \"container_status\" = 'running' AND \"container_name\" !~ /^k8s_POD_.*$/) AND $timeFilter GROUP BY \"container_name\"",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "docker.group", "operator": "=~", "value": "/^$Docker_Stack$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "container_status", "operator": "=", "value": "running" },
      { "condition": "AND", "key": "container_name", "operator": "!~", "value": "/^k8s_POD_.*$/" },
      {
       "condition": "AND",
       "key": "container_name",
       "operator": "=~",
       "value": "/^k8s_(influxdb|mysql|grafana|nginx|wordpress|phpmyadmin|ftps).*$/"
      }
     ]
    }
   ]
  },
  {
   "title": "Mem Usage %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "query": "SELECT mean(\"usage_percent\") FROM \"docker_container_mem\" WHERE (\"docker.group\" =~ /^$Docker_Stack$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval), \"container_name\" fill(none)",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "docker.group", "operator": "=~", "value": "/^$Docker_Stack$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" },
      {
       "condition": "AND",
       "key": "container_name",
       "operator": "=~",
       "value": "/^k8s_(influxdb|mysql|grafana|nginx|wordpress|phpmyadmin|ftps).*$/"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "docker.group", "operator": "=~", "value": "/^$Docker_Stack$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" },
      {
       "condition": "AND",
       "key": "container_name",
       "operator": "=~",
       "value": "/^k8s_(influxdb|mysql|grafana|nginx|wordpress|phpmyadmin|ftps).*$/"
      }
     ]
    }
   ]
  },
  {
   "title": "Traffic In",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_container_name RX traffic",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "docker.group", "operator": "=~", "value": "/^$Docker_Stack$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" },
      {
       "condition": "AND",
       "key": "container_name",
       "operator": "=~",
       "value": "/^k8s_(influxdb|mysql|grafana|nginx|wordpress|phpmyadmin|ftps).*$/"
      }
     ]
    }
   ]
  },
  {
   "title": "Traffic Out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_container_name TX traffic",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "docker.group", "operator": "=~", "value": "/^$Docker_Stack$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" },
      {
       "condition": "AND",
       "key": "container_name",
       "operator": "=~",
       "value": "/^k8s_(influxdb|mysql|grafana|nginx|wordpress|phpmyadmin|ftps).*$/"
      }
     ]
    }
   ]
  }
 ]
}