#!/bin/bash

rm -rf /tmp/correction

git clone https://github.com/Night-squad/libft-war-machine-v2019 /tmp/correction/warmachine
git clone https://github.com/alelievr/libft-unit-test /tmp/correction/unit
git clone $1 /tmp/correction/libft

cd /tmp/correction/unit
make f

read -p "Pres any key to continue..." -n1 -s

cd /tmp/correction/libft
make fclean

cd /tmp/correction/warmachine
sh grademe.sh
sh grademe.sh
