apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-influxdb
  labels:
    run: influxdb
spec:
  storageClassName: influxdb
  capacity:
    storage: 700Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/influxdb"
