apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: ft_services
spec:
  type: LoadBalancer
  ports:
    - port: 5050
      protocol: TCP
      name: https-wordpress
      targetPort: 443
      nodePort: 30550
  selector:
      run: wordpress
