apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: ft_services
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      protocol: TCP
      name: https-phpmyadmin
      targetPort: 443
      nodePort: 30500
  selector:
    run: phpmyadmin

