apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: ft_services
spec:
  type: ClusterIP
  ports:
    - port: 3306
      protocol: TCP
      name: sql
      targetPort: 3306
  selector:
      run: mysql
