apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: ft_services
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      name: http-nginx
      targetPort: 80
      nodePort: 30080
    - port: 443
      protocol: TCP
      name: https-nginx
      targetPort: 443
      nodePort: 30443
  selector:
    run: nginx
