apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: ft_services
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      protocol: TCP
      name: https-grafana
      targetPort: 3000
      nodePort: 30300
  selector:
      run: grafana
