title: Millefeuille42 Guide
email: mlabouri@mail.millefeuille.fail
description: >-
  A guide to 42 new Cursus
url: "cv.millefeuille.fail"
github_username:  Millefeuille42
  
title: Millefeuille42 Guide
description : A guide to 42's new Cursus Projects

# Build settings
theme: jekyll-theme-hacker
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
